#!/usr/bin/env python3
"""Build the reproducible native/WebAssembly GRMHD continuation resources.

The history and the full double-precision t=800 checkpoint are produced by
``generate-grmhd.py`` from the pinned iharm2d_v3 commit.  This script validates
that canonical checkpoint, compiles the identical deterministic core for native
and wasm32, and records the compiler/source/resource hashes used by the browser
runtime.  It never reconstructs a float64 restart from the float32 display data.
"""
import argparse
import array
import gzip
import hashlib
import json
import shutil
import struct
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "dist" / "data"
SOLVER = ROOT / "dist" / "solver"
SOURCE = ROOT / "tools" / "grmhd-runtime.rs"
CHECKPOINT_MAGIC = b"GRMHDCP1"
CHECKPOINT_HEADER = "<8sIIII d II"
CELLS = 64 * 64
COMPONENTS = 12
BOUNDARY_ROWS = 2


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def read_history():
    metadata_path = DATA / "grmhd-torus.json"
    history_path = DATA / "grmhd-torus.f32.gz"
    metadata = json.loads(metadata_path.read_text())
    raw = gzip.decompress(history_path.read_bytes())
    if len(raw) != metadata["bytes"] or sha256(raw) != metadata["sha256"]:
        raise RuntimeError("published GRMHD history does not match its metadata")
    records = array.array("f")
    records.frombytes(raw)
    if len(records) != len(metadata["times"]) * CELLS * COMPONENTS:
        raise RuntimeError("published GRMHD history has an unexpected record count")
    if struct.pack("=f", 1.0) != struct.pack("<f", 1.0):
        records.byteswap()
    return metadata, records


def load_checkpoint(metadata):
    checkpoint_path = DATA / "grmhd-torus.checkpoint.bin.gz"
    checkpoint_meta = metadata.get("checkpoint")
    if not checkpoint_meta or checkpoint_meta.get("precision") != "float64":
        raise RuntimeError("metadata must reference a float64 checkpoint generated by generate-grmhd.py")
    if not checkpoint_path.exists():
        raise RuntimeError("canonical checkpoint is missing; run tools/generate-grmhd.py first")
    raw = gzip.decompress(checkpoint_path.read_bytes())
    cells = int(metadata["resolution"][0]) * int(metadata["resolution"][1])
    components = len(metadata["components"])
    expected_state_count = cells * components
    if sha256(raw) != checkpoint_meta["sha256"] or len(raw) != checkpoint_meta["bytes"]:
        raise RuntimeError("canonical checkpoint does not match its metadata")
    if len(raw) < struct.calcsize(CHECKPOINT_HEADER):
        raise RuntimeError("canonical checkpoint is truncated")
    header = struct.unpack(CHECKPOINT_HEADER, raw[:struct.calcsize(CHECKPOINT_HEADER)])
    magic, version, header_cells, header_components, boundary_rows, time, boundary_width, _ = header
    if magic != CHECKPOINT_MAGIC or version != 1 or header_cells != cells or header_components != components:
        raise RuntimeError("canonical checkpoint header does not match the history metadata")
    if boundary_rows != checkpoint_meta["boundaryRows"] or boundary_width != checkpoint_meta["boundaryWidth"]:
        raise RuntimeError("canonical checkpoint boundary metadata is inconsistent")
    if abs(time - float(metadata["times"][-1])) > 1e-9 or checkpoint_meta["stateCount"] != expected_state_count:
        raise RuntimeError("canonical checkpoint time or state count is inconsistent")
    boundary_count = boundary_rows * boundary_width * components
    expected_bytes = struct.calcsize(CHECKPOINT_HEADER) + expected_state_count * 8 + boundary_count * 8
    if len(raw) != expected_bytes:
        raise RuntimeError("canonical checkpoint has an unexpected byte length")
    # Keep the two explicit radial rows tied to the full state; the producer
    # and the browser validator therefore agree on both precision and layout.
    state_offset = struct.calcsize(CHECKPOINT_HEADER)
    state = struct.unpack("<" + "d" * expected_state_count, raw[state_offset:state_offset + expected_state_count * 8])
    boundary_offset = state_offset + expected_state_count * 8
    boundary = struct.unpack("<" + "d" * boundary_count, raw[boundary_offset:])
    if boundary_rows == BOUNDARY_ROWS:
        row_values = boundary_width * components
        if tuple(boundary[:row_values]) != tuple(state[:row_values]) or tuple(boundary[row_values:]) != tuple(state[-row_values:]):
            raise RuntimeError("canonical checkpoint boundary rows do not match the full state")
    metadata = dict(metadata)
    metadata["version"] = max(2, int(metadata.get("version", 1)))
    # Preserve the generator's provenance block byte-for-byte instead of
    # rewriting it from the float32 history used for GPU playback.
    return raw, metadata


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rustc", default=shutil.which("rustc"), help="rustc executable with wasm32-unknown-unknown installed")
    parser.add_argument("--skip-native", action="store_true", help="only build the browser wasm resource")
    args = parser.parse_args()
    if not args.rustc:
        raise SystemExit("rustc with the wasm32-unknown-unknown target is required")
    SOLVER.mkdir(parents=True, exist_ok=True)
    metadata, _ = read_history()
    checkpoint_raw, metadata = load_checkpoint(metadata)
    del checkpoint_raw
    with tempfile.TemporaryDirectory(prefix="interstellar-grmhd-runtime-") as build_dir:
        native_path = Path(build_dir) / "grmhd-runtime-native"
        wasm_path = SOLVER / "grmhd-runtime.wasm"
        wasm_command = [args.rustc, "--target=wasm32-unknown-unknown", "-O", "--crate-type=cdylib", "-C", "panic=abort", "-o", str(wasm_path), str(ROOT / "tools" / "grmhd-runtime.rs")]
        subprocess.run(wasm_command, check=True)
        native_command = None
        if not args.skip_native:
            native_command = [args.rustc, "-O", "-C", "panic=abort", "-o", str(native_path), str(SOURCE)]
            subprocess.run(native_command, check=True)
        rustc_version = subprocess.check_output([args.rustc, "--version"], text=True).splitlines()[0]
    wasm_bytes = wasm_path.read_bytes()
    build_metadata = {
        "formatVersion": 1,
        "api": ["grmhd_init", "grmhd_advance", "grmhd_snapshot", "grmhd_destroy"],
        "source": "tools/grmhd-runtime.rs",
        "sourceSha256": sha256(SOURCE.read_bytes()),
        "upstreamRepository": metadata["repository"],
        "upstreamCommit": metadata["commit"],
        "historySha256": metadata["sha256"],
        "checkpointSha256": metadata["checkpoint"]["sha256"],
        "compiler": rustc_version,
        "wasmSha256": sha256(wasm_bytes),
        "wasmBytes": len(wasm_bytes),
        "doublePrecision": True,
        "sharedMemory": False,
        "nativeCommand": ["rustc", "-O", "-C", "panic=abort", "-o", "<temporary>/grmhd-runtime-native", "tools/grmhd-runtime.rs"] if native_command else None,
        "wasmCommand": ["rustc", "--target=wasm32-unknown-unknown", "-O", "--crate-type=cdylib", "-C", "panic=abort", "-o", "dist/solver/grmhd-runtime.wasm", "tools/grmhd-runtime.rs"],
        "stepMax": 2.0,
        "snapshotInterval": 20.0,
        "cacheSlots": 128,
        "diagnostics": ["time", "finite", "minDensity", "minInternal", "massResidual", "internalResidual", "maxCoordinateDivB", "velocityNormDrift", "velocityDrift", "acceptedSteps", "positive", "maxVelocityNormError"],
    }
    (SOLVER / "grmhd-runtime.json").write_text(json.dumps(build_metadata, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps({"wasm": str(wasm_path), "wasmSha256": build_metadata["wasmSha256"], "checkpoint": metadata["checkpoint"]}, indent=2))


if __name__ == "__main__":
    main()
